### ISSUE TITLE
App meta

### ISSUE THREAD

**Issue by bschlagel** [hyperlink-academy/minilink#12]
A few more general things to get set up before launch:

- [ ] configure app on real domain
- [ ] update doc titles based on first header block (maybe second block = description?) for nice preview rendering both in linked docs and external social media links etc.
- [ ] add a favicon…probably something leafy :)
